### ISSUE TITLE
Get "Only support 64x64 image" error when dumping network infor of dcgan

### ISSUE THREAD

**Issue by puddingfjz** [tlc-pack/tenset#28]
When I was dumping the network information of dcgan using the dump_network_info.py (I modified this file to only dump the information of dcgan), I got the following error:

> Traceback (most recent call last):
  File "dump_network_info.py", line 243, in <module>
    dump_network(key, target)
  File "dump_network_info.py", line 122, in dump_network
    mod, params, inputs = get_network_with_key(network_key)
  File "dump_network_info.py", line 103, in get_network_with_key
    mod, params = relay.testing.dcgan.get_workload(
  File "/usr/tvm/python/tvm/relay/testing/dcgan.py", line 170, in get_workload
    net = get_net(batch_size, random_len, oshape=oshape, ngf=ngf, layout=layout, dtype=dtype)
  File "/usr/tvm/python/tvm/relay/testing/dcgan.py", line 87, in get_net
    assert oshape[-1] == 64, "Only support 64x64 image"
AssertionError: Only support 64x64 image

Can I directly delete the assert statements in the file "/usr/tvm/python/tvm/relay/testing/dcgan.py"?

Thanks!

**Comment by merrymercy** [comment]
You can try and verify it, but I guess some shapes will be wrong.
