### ISSUE TITLE
When executing `python measure_programs.py "--target=cuda"`, I get some errors.

### ISSUE THREAD

**Issue by zhaiyi000** [tlc-pack/tenset#31]
Hi, mercy

When executing `python measure_programs.py "--target=cuda"`, I get some errors. Those errors are tvm error and timeout error.
i try to modify the build time to 30 seconds and run time to 30 seconds, but these is no difference.

what target should i specify when i measure  programs with 2080Ti? I didn't find documentation to guide setting target when using cuda. Is it enough to just set `--target=cuda`?

Thank you, mercy~

```
  6: ffi_call_unix64
  5: TVMArrayFree
        at /root/tenset/src/runtime/ndarray.cc:295
  4: _ZN3tvm7runtime7NDArray8Int
  3: tvm::runtime::NDArray::FFIDecRef(DLTensor*)
        at /root/tenset/include/tvm/runtime/ndarray.h:383
  2: tvm::runtime::Object::DecRef()
        at /root/tenset/include/tvm/runtime/object.h:781
  1: tvm::runtime::NDArray::Internal::DefaultDeleter(tvm::runtime::Object*)
  0: tvm::runtime::CUDADeviceAPI::FreeDataSpace(DLContext, void*)
        at /root/tenset/src/runtime/cuda/cuda_device_api.cc:127
  File "/root/tenset/src/runtime/cuda/cuda_device_api.cc", line 127
TVMError: ---------------------------------------------------------------
An internal invariant was violated during the execution of TVM.
Please read TVM's error reporting guidelines.
More details can be found here: https://discuss.tvm.ai/t/error-reporting/7793.
---------------------------------------------------------------
  Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading == false: CUDA: misaligned address
Exception ignored in: <function NDArrayBase.__del__ at 0x7f92d8afc820>
Traceback (most recent call last):
  File "/root/tenset/python/tvm/_ffi/_ctypes/ndarray.py", line 82, in __del__
    check_call(_LIB.TVMArrayFree(self.handle))
  File "/root/tenset/python/tvm/_ffi/base.py", line 346, in check_call
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  43: 0xffffffffffffffff
  42: __clone
  41: start_thread
        at /build/glibc-uZu3wS/glibc-2.27/nptl/pthread_create.c:463
  40: 0x0000000000619066
  39: 0x00000000006390f7
  38: PyObject_Call
  37: 0x0000000000537506
  36: _PyObject_Call_Prepend
  35: _PyEval_EvalFrameDefault
  34: PyVectorcall_Call
  33: 0x00000000005ce97f
  32: _PyFunction_Vectorcall
  31: 0x000000000045b756
  30: 0x0000000000609bbf
  29: _PyFunction_Vectorcall
  28: 0x000000000045b756
  27: 0x0000000000609bbf
  26: _PyFunction_Vectorcall
  25: _PyEval_EvalFrameDefault
  24: PyVectorcall_Call
  23: _PyFunction_Vectorcall
  22: _PyEval_EvalCodeWithName
  21: _PyEval_EvalFrameDefault
  20: PyVectorcall_Call
  19: _PyFunction_Vectorcall
  18: 0x0000000000500cb4
  17: 0x0000000000501310
  16: 0x0000000000535307
  15: PyObject_CallFinalizerFromDealloc
  14: 0x00000000005fa0c5
  13: 0x0000000000535c2b
  12: _PyFunction_Vectorcall
  11: 0x000000000045c107
  10: _PyObject_MakeTpCall
  9: 0x00007f939f8cc763
  8: _ctypes_callproc
  7: ffi_call
  6: ffi_call_unix64
  5: TVMArrayFree
        at /root/tenset/src/runtime/ndarray.cc:295
  4: _ZN3tvm7runtime7NDArray8Int
  3: tvm::runtime::NDArray::FFIDecRef(DLTensor*)
        at /root/tenset/include/tvm/runtime/ndarray.h:383
  2: tvm::runtime::Object::DecRef()
        at /root/tenset/include/tvm/runtime/object.h:781
  1: tvm::runtime::NDArray::Internal::DefaultDeleter(tvm::runtime::Object*)
  0: tvm::runtime::CUDADeviceAPI::FreeDataSpace(DLContext, void*)
        at /root/tenset/src/runtime/cuda/cuda_device_api.cc:127
  File "/root/tenset/src/runtime/cuda/cuda_device_api.cc", line 127
TVMError: ---------------------------------------------------------------
An internal invariant was violated during the execution of TVM.
Please read TVM's error reporting guidelines.
More details can be found here: https://discuss.tvm.ai/t/error-reporting/7793.
---------------------------------------------------------------
  Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading == false: CUDA: misaligned address
Exception ignored in: <function NDArrayBase.__del__ at 0x7f92d8afc820>
Traceback (most recent call last):
  File "/root/tenset/python/tvm/_ffi/_ctypes/ndarray.py", line 82, in __del__
    check_call(_LIB.TVMArrayFree(self.handle))
  File "/root/tenset/python/tvm/_ffi/base.py", line 346, in check_call
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  42: 0xffffffffffffffff
  41: __clone
  40: start_thread
        at /build/glibc-uZu3wS/glibc-2.27/nptl/pthread_create.c:463
  39: 0x0000000000619066
  38: 0x00000000006390f7
  37: PyObject_Call
  36: 0x0000000000537506
  35: _PyObject_Call_Prepend
  34: _PyEval_EvalFrameDefault
  33: PyVectorcall_Call
  32: 0x00000000005ce97f
  31: _PyFunction_Vectorcall
  30: 0x000000000045b756
  29: 0x0000000000609bbf
  28: _PyFunction_Vectorcall
  27: 0x000000000045b756
  26: 0x0000000000609bbf
  25: _PyFunction_Vectorcall
  24: _PyEval_EvalFrameDefault
  23: PyVectorcall_Call
  22: _PyFunction_Vectorcall
  21: _PyEval_EvalCodeWithName
  20: _PyEval_EvalFrameDefault
  19: PyVectorcall_Call
  18: _PyFunction_Vectorcall
  17: 0x0000000000500cb4
  16: 0x0000000000535307
  15: PyObject_CallFinalizerFromDealloc
  14: 0x00000000005fa0c5
  13: 0x0000000000535c2b
  12: _PyFunction_Vectorcall
  11: 0x000000000045c107
  10: _PyObject_MakeTpCall
  9: 0x00007f939f8cc763
  8: _ctypes_callproc
  7: ffi_call
  6: ffi_call_unix64
  5: TVMArrayFree
        at /root/tenset/src/runtime/ndarray.cc:295
  4: _ZN3tvm7runtime7NDArray8Int
  3: tvm::runtime::NDArray::FFIDecRef(DLTensor*)
        at /root/tenset/include/tvm/runtime/ndarray.h:383
  2: tvm::runtime::Object::DecRef()
        at /root/tenset/include/tvm/runtime/object.h:781
  1: tvm::runtime::NDArray::Internal::DefaultDeleter(tvm::runtime::Object*)
  0: tvm::runtime::CUDADeviceAPI::FreeDataSpace(DLContext, void*)
        at /root/tenset/src/runtime/cuda/cuda_device_api.cc:127
  File "/root/tenset/src/runtime/cuda/cuda_device_api.cc", line 127
TVMError: ---------------------------------------------------------------
An internal invariant was violated during the execution of TVM.
Please read TVM's error reporting guidelines.
More details can be found here: https://discuss.tvm.ai/t/error-reporting/7793.
---------------------------------------------------------------
  Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading == false: CUDA: misaligned address
terminate called after throwing an instance of 'tvm::runtime::InternalError'
  what():  [16:04:22] /root/tenset/src/runtime/cuda/cuda_module.cc:61: CUDAError: cuModuleUnload(module_[i]) failed with error: CUDA_ERROR_MISALIGNED_ADDRESS
Stack trace:
  0: tvm::runtime::CUDAModuleNode::~CUDAModuleNode()
        at /root/tenset/src/runtime/cuda/cuda_module.cc:61
  1: tvm::runtime::SimpleObjAllocator::Handler<tvm::runtime::CUDAModuleNode>::Deleter_(tvm::runtime::Object*)
        at /root/tenset/include/tvm/runtime/memory.h:138
  2: tvm::runtime::Object::DecRef()
        at /root/tenset/include/tvm/runtime/object.h:781
  3: tvm::runtime::ObjectPtr<tvm::runtime::Object>::reset()
        at /root/tenset/include/tvm/runtime/object.h:442
  4: tvm::runtime::ObjectPtr<tvm::runtime::Object>::~ObjectPtr()
        at /root/tenset/include/tvm/runtime/object.h:396
  5: tvm::runtime::ObjectRef::~ObjectRef()
        at /root/tenset/include/tvm/runtime/object.h:502
  6: tvm::runtime::Module::~Module()
        at /root/tenset/include/tvm/runtime/module.h:48
  7: void std::_Destroy<tvm::runtime::Module>(tvm::runtime::Module*)
        at /usr/include/c++/7/bits/stl_construct.h:98
  8: void std::_Destroy_aux<false>::__destroy<tvm::runtime::Module*>(tvm::runtime::Module*, tvm::runtime::Module*)
        at /usr/include/c++/7/bits/stl_construct.h:108
  9: void std::_Destroy<tvm::runtime::Module*>(tvm::runtime::Module*, tvm::runtime::Module*)
        at /usr/include/c++/7/bits/stl_construct.h:137
  10: void std::_Destroy<tvm::runtime::Module*, tvm::runtime::Module>(tvm::runtime::Module*, tvm::runtime::Module*, std::allocator<tvm::runtime::Module>&)
        at /usr/include/c++/7/bits/stl_construct.h:206
  11: std::vector<tvm::runtime::Module, std::allocator<tvm::runtime::Module> >::~vector()
        at /usr/include/c++/7/bits/stl_vector.h:434
  12: tvm::runtime::ModuleNode::~ModuleNode()
        at /root/tenset/include/tvm/runtime/module.h:114
  13: tvm::runtime::LibraryModuleNode::~LibraryModuleNode()
        at /root/tenset/src/runtime/library_module.cc:38
  14: tvm::runtime::SimpleObjAllocator::Handler<tvm::runtime::LibraryModuleNode>::Deleter_(tvm::runtime::Object*)
        at /root/tenset/include/tvm/runtime/memory.h:138
  15: tvm::runtime::Object::DecRef()
        at /root/tenset/include/tvm/runtime/object.h:781
  16: tvm::runtime::ObjectPtr<tvm::runtime::Object>::reset()
        at /root/tenset/include/tvm/runtime/object.h:442
  17: tvm::runtime::ObjectPtr<tvm::runtime::Object>::~ObjectPtr()
        at /root/tenset/include/tvm/runtime/object.h:396
  18: ~<lambda>
        at /root/tenset/src/runtime/library_module.cc:73
  19: _M_destroy
        at /usr/include/c++/7/bits/std_function.h:207
  20: _M_manager
        at /usr/include/c++/7/bits/std_function.h:231
  21: std::_Function_base::~_Function_base()
        at /usr/include/c++/7/bits/std_function.h:276
  22: std::function<void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)>::~function()
        at /usr/include/c++/7/bits/std_function.h:389
  23: tvm::runtime::PackedFunc::~PackedFunc()
        at /root/tenset/include/tvm/runtime/packed_func.h:75
  24: ~<lambda>
        at /root/tenset/src/runtime/rpc/rpc_module.cc:370
  25: _M_destroy
        at /usr/include/c++/7/bits/std_function.h:207
  26: _M_manager
        at /usr/include/c++/7/bits/std_function.h:231
  27: std::_Function_base::~_Function_base()
        at /usr/include/c++/7/bits/std_function.h:276
  28: std::function<void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)>::~function()
        at /usr/include/c++/7/bits/std_function.h:389
  29: tvm::runtime::PackedFunc::~PackedFunc()
        at /root/tenset/include/tvm/runtime/packed_func.h:75
  30: TVMFuncFree
        at /root/tenset/src/runtime/c_runtime_api.cc:463
  31: ffi_call_unix64
  32: ffi_call
  33: _ctypes_callproc
  34: 0x00007f939f8cc763
  35: _PyObject_MakeTpCall
  36: 0x000000000045c107
  37: _PyFunction_Vectorcall
  38: 0x0000000000535c2b
  39: 0x00000000005fa0c5
  40: PyObject_CallFinalizerFromDealloc
  41: 0x0000000000535307
  42: 0x00000000005ce6d4
  43: 0x000000000052cd24
  44: 0x00000000005d4882
  45: 0x0000000000500cb4
  46: _PyFunction_Vectorcall
  47: PyVectorcall_Call
  48: _PyEval_EvalFrameDefault
  49: _PyEval_EvalCodeWithName
  50: _PyFunction_Vectorcall
  51: PyVectorcall_Call
  52: _PyEval_EvalFrameDefault
  53: _PyFunction_Vectorcall
  54: 0x0000000000609bbf
  55: 0x000000000045b756
  56: _PyFunction_Vectorcall
  57: 0x0000000000609bbf
  58: 0x000000000045b756
  59: _PyFunction_Vectorcall
  60: 0x00000000005ce97f
  61: PyVectorcall_Call
  62: _PyEval_EvalFrameDefault
  63: _PyObject_Call_Prepend
  64: 0x0000000000537506
  65: PyObject_Call
  66: 0x00000000006390f7
  67: 0x0000000000619066
  68: start_thread
        at /build/glibc-uZu3wS/glibc-2.27/nptl/pthread_create.c:463
  69: __clone
  70: 0xffffffffffffffff


*T*T*T*T*T*T*E*T*T*T*T*E*T*T*E*T*T*T*E*T*E*T*T*T*T*E*T*E*T*T*T*E*T*T*T*T*E*T*E*E*T*EException ignored in: <function NDArrayBase.__del__ at 0x7f92d8afc820>
Traceback (most recent call last):
  File "/root/tenset/python/tvm/_ffi/_ctypes/ndarray.py", line 82, in __del__
    check_call(_LIB.TVMArrayFree(self.handle))
  File "/root/tenset/python/tvm/_ffi/base.py", line 346, in check_call
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  43: 0xffffffffffffffff
  42: __clone
  41: start_thread
        at /build/glibc-uZu3wS/glibc-2.27/nptl/pthread_create.c:463
  40: 0x0000000000619066
  39: 0x00000000006390f7
  38: PyObject_Call
  37: 0x0000000000537506
  36: _PyObject_Call_Prepend
  35: _PyEval_EvalFrameDefault
  34: PyVectorcall_Call
  33: 0x00000000005ce97f
  32: _PyFunction_Vectorcall
  31: 0x000000000045b756
  30: 0x0000000000609bbf
  29: _PyFunction_Vectorcall
  28: 0x000000000045b756
  27: 0x0000000000609bbf
  26: _PyFunction_Vectorcall
  25: _PyEval_EvalFrameDefault
  24: PyVectorcall_Call
  23: _PyFunction_Vectorcall
  22: _PyEval_EvalCodeWithName
  21: _PyEval_EvalFrameDefault
  20: PyVectorcall_Call
  19: _PyFunction_Vectorcall
  18: 0x0000000000500cb4
  17: 0x0000000000501310
  16: 0x0000000000535307
  15: PyObject_CallFinalizerFromDealloc
  14: 0x00000000005fa0c5
  13: 0x0000000000535c2b
  12: _PyFunction_Vectorcall
  11: 0x000000000045c107
  10: _PyObject_MakeTpCall
  9: 0x00007f939f8cc763
  8: _ctypes_callproc
  7: ffi_call
  6: ffi_call_unix64
  5: TVMArrayFree
        at /root/tenset/src/runtime/ndarray.cc:295
  4: _ZN3tvm7runtime7NDArray8Int
  3: tvm::runtime::NDArray::FFIDecRef(DLTensor*)
        at /root/tenset/include/tvm/runtime/ndarray.h:383
  2: tvm::runtime::Object::DecRef()
        at /root/tenset/include/tvm/runtime/object.h:781
  1: tvm::runtime::NDArray::Internal::DefaultDeleter(tvm::runtime::Object*)
  0: tvm::runtime::CUDADeviceAPI::FreeDataSpace(DLContext, void*)
        at /root/tenset/src/runtime/cuda/cuda_device_api.cc:127
  File "/root/tenset/src/runtime/cuda/cuda_device_api.cc", line 127
TVMError: ---------------------------------------------------------------
An internal invariant was violated during the execution of TVM.
Please read TVM's error reporting guidelines.
More details can be found here: https://discuss.tvm.ai/t/error-reporting/7793.
---------------------------------------------------------------
  Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading == false: CUDA: misaligned address
Exception ignored in: <function NDArrayBase.__del__ at 0x7f92d8afc820>
Traceback (most recent call last):
  File "/root/tenset/python/tvm/_ffi/_ctypes/ndarray.py", line 82, in __del__
    check_call(_LIB.TVMArrayFree(self.handle))
  File "/root/tenset/python/tvm/_ffi/base.py", line 346, in check_call
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  43: 0xffffffffffffffff
  42: __clone
  41: start_thread
        at /build/glibc-uZu3wS/glibc-2.27/nptl/pthread_create.c:463
  40: 0x0000000000619066
  39: 0x00000000006390f7
  38: PyObject_Call
  37: 0x0000000000537506
  36: _PyObject_Call_Prepend
  35: _PyEval_EvalFrameDefault
  34: PyVectorcall_Call
  33: 0x00000000005ce97f
  32: _PyFunction_Vectorcall
  31: 0x000000000045b756
  30: 0x0000000000609bbf
  29: _PyFunction_Vectorcall
  28: 0x000000000045b756
  27: 0x0000000000609bbf
  26: _PyFunction_Vectorcall
  25: _PyEval_EvalFrameDefault
  24: PyVectorcall_Call
  23: _PyFunction_Vectorcall
  22: _PyEval_EvalCodeWithName
  21: _PyEval_EvalFrameDefault
  20: PyVectorcall_Call
  19: _PyFunction_Vectorcall
  18: 0x0000000000500cb4
  17: 0x0000000000501310
  16: 0x0000000000535307
  15: PyObject_CallFinalizerFromDealloc
  14: 0x00000000005fa0c5
  13: 0x0000000000535c2b
  12: _PyFunction_Vectorcall
  11: 0x000000000045c107
  10: _PyObject_MakeTpCall
  9: 0x00007f939f8cc763
  8: _ctypes_callproc
  7: ffi_call
  6: ffi_call_unix64
  5: TVMArrayFree
        at /root/tenset/src/runtime/ndarray.cc:295
  4: _ZN3tvm7runtime7NDArray8Int
  3: tvm::runtime::NDArray::FFIDecRef(DLTensor*)
        at /root/tenset/include/tvm/runtime/ndarray.h:383
  2: tvm::runtime::Object::DecRef()
        at /root/tenset/include/tvm/runtime/object.h:781
  1: tvm::runtime::NDArray::Internal::DefaultDeleter(tvm::runtime::Object*)
  0: tvm::runtime::CUDADeviceAPI::FreeDataSpace(DLContext, void*)
        at /root/tenset/src/runtime/cuda/cuda_device_api.cc:127
  File "/root/tenset/src/runtime/cuda/cuda_device_api.cc", line 127
TVMError: ---------------------------------------------------------------
An internal invariant was violated during the execution of TVM.
Please read TVM's error reporting guidelines.
```

**Comment by merrymercy** [comment]
For CUDA backend, the master branch has some problems. Maybe you can try this branch https://github.com/tlc-pack/tenset/pull/4

**Comment by joapolarbear** [comment]
Hi. Have you solved this problem? I encountered a similar problem.  When running `python3 measure_programs.py --target cuda`, it raises the following errors.  I use the latest version of [TVM].(https://github.com/apache/tvm/commit/778db2f34f4c73fd362e6192dbdc1972bdd37999)
 
```python
Load all tasks...
tasks: range(start=0, end=2308, step=1)
########## Task 0, FLOPs = -1.0 ##########
placeholder = PLACEHOLDER [1, 14, 14, 480]
tensor(ax0, ax1, ax2, ax3) += placeholder[ax0, ((ax1*14) + rv0), ((ax2*14) + rv1), ax3]
tensor(ax0, ax1, ax2, ax3) = (tensor[ax0, ax1, ax2, ax3]/(float32((select((bool)1, ((ax1 + 1)*14), (((ax1 + 1)*14) + 1)) - (ax1*14)))*float32((select((bool)1, ((ax2 + 1)*14), (((ax2 + 1)*14) + 1)) - (ax2*14)))))

[19:16:48] /home/tiger/tvm/src/target/target_kind.cc:163: Warning: Unable to detect CUDA version, default to "-arch=sm_20" instead
===== task: 0    programs: 0/607 =====
Traceback (most recent call last):
  File "measure_programs.py", line 114, in <module>
    remeasure_file(i, task, target, args.target_host, args.batch_size, measurer_kwargs)
  File "measure_programs.py", line 61, in remeasure_file
    res_batch = measurer.measure(task, empty_policy, inp_batch)
  File "/usr/local/lib/python3.7/dist-packages/tvm-0.9.dev237+g328cbb064-py3.7-linux-x86_64.egg/tvm/runtime/object.py", line 65, in __getattr__
    return _ffi_node_api.NodeGetAttr(self, name)
  File "/usr/local/lib/python3.7/dist-packages/tvm-0.9.dev237+g328cbb064-py3.7-linux-x86_64.egg/tvm/_ffi/_ctypes/packed_func.py", line 237, in __call__
    raise get_last_ffi_error()
TypeError: Traceback (most recent call last):
  3: TVMFuncCall
  2: _ZNSt17_Function_handlerI
  1: tvm::NodeGetAttr(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  0: tvm::ReflectionVTable::GetAttr(tvm::runtime::Object*, tvm::runtime::String const&) const
  File "/home/tiger/tvm/include/tvm/node/reflection.h", line 390

TypeError: auto_scheduler.ProgramMeasurer is not registered via TVM_REGISTER_NODE_TYPE
```

Using the branch [#4](https://github.com/tlc-pack/tenset/pull/4) doesn't work for me. Any suggestions? Thanks~

**Comment by zhaiyi000** [comment]
1. Recommend not to use the latest version of TVM and use this repository directly;
2. for CUDA backend, try using this branch; [#4](https://github.com/tlc-pack/tenset/pull/4) [merry's answer](https://github.com/tlc-pack/tenset/issues/31#issuecomment-1146713487)
3. Sometimes this problem occurs when using python multi-process, and I don't know why. `TypeError: auto_scheduler.ProgramMeasurer is not registered via TVM_REGISTER_NODE_TYPE`
